spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.skyhigh: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000
